

---- Start Log 1 ----
Log#: 1
Datetime:  2024-12-10 14:39:32.942671
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1166, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 1 ----


---- Start Log 2 ----
Log#: 2
Datetime:  2024-12-10 14:50:27.783340
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1167, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 2 ----


---- Start Log 3 ----
Log#: 3
Datetime:  2024-12-10 14:55:49.253606
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1167, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 3 ----


---- Start Log 4 ----
Log#: 4
Datetime:  2024-12-10 15:04:10.359824
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1167, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 4 ----


---- Start Log 5 ----
Log#: 5
Datetime:  2024-12-10 15:07:39.877516
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1168, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 5 ----


---- Start Log 6 ----
Log#: 6
Datetime:  2024-12-10 15:25:23.227996
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1168, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 6 ----


---- Start Log 7 ----
Log#: 7
Datetime:  2024-12-10 15:31:51.259636
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1169, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 11, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=200)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 7 ----


---- Start Log 8 ----
Log#: 8
Datetime:  2024-12-10 15:50:31.434981
User:  cjrober5@ncsu.edu
Type: TypeError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 14, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=30)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1169, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 15, in __init__
    except paramiko.ssh_exception as exc:
TypeError: catching classes that do not inherit from BaseException is not allowed
---- End Log 8 ----


---- Start Log 9 ----
Log#: 9
Datetime:  2024-12-10 15:53:04.209194
User:  cjrober5@ncsu.edu
Type: TimeoutError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 1169, in saving_development
    ssh_call = AerpawSsh(hostname=aerpaw_ops_host, username=aerpaw_ops_user, keyfile=aerpaw_ops_key_file)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/server/ops_ssh_utils.py", line 14, in __init__
    self.client.connect(hostname=hostname, username=username, pkey=self.key, banner_timeout=30)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
---- End Log 9 ----


---- Start Log 10 ----
Log#: 10
Datetime:  2024-12-12 15:47:59.737166
User:  cjrober5@ncsu.edu
Type: ProgrammingError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "exit_code" of relation "error_handling_aerpawthread" does not exist
LINE 1: ...thread" ("user_id", "thread_start", "thread_end", "exit_code...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/api/experiment_utils.py", line 90, in active_development_to_saving_development
    aerpaw_thread = start_aerpaw_thread(request.user)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/error_handling/error_dashboard.py", line 129, in start_aerpaw_thread
    new_thread.save()
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1160, in _save_table
    results = self._do_insert(
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1201, in _do_insert
    return manager._insert(
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "exit_code" of relation "error_handling_aerpawthread" does not exist
LINE 1: ...thread" ("user_id", "thread_start", "thread_end", "exit_code...
                                                             ^

---- End Log 10 ----


---- Start Log 11 ----
Log#: 11
Datetime:  2024-12-18 11:49:59.096186
User:  cjrober5@ncsu.edu
Type: AttributeError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/views.py", line 224, in experiment_detail
    if session_obj.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
---- End Log 11 ----


---- Start Log 12 ----
Log#: 12
Datetime:  2024-12-18 13:21:36.227835
User:  cjrober5@ncsu.edu
Type: AttributeError
Traceback (most recent call last):
  File "/Users/christopherroberts/Documents/aerpaw/chris-development/aerpaw-portal/portal/apps/experiments/views.py", line 224, in experiment_detail
    if session_obj.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
---- End Log 12 ----
